// SPDX-License-Identifier: GPL-3.0-or-later
import { formatCodepoint } from "./unicode";

/**
 * Generates the server-side triplet a painted screen needs, in the shape NEXT settled
 * on with the locker module (the only one of its kind with tests): a `<Name>Glyphs`
 * holding codepoints and measured advances, a `<Name>Layout` of hotspot constants, and
 * a `<Name>GlyphsTest` cursor simulator.
 *
 * Scaffold means scaffold: these are NEW files for a NEW screen. Slotify never patches
 * an existing Layout — hand-tuned click code is not machine-mergeable.
 */

export interface ScaffoldSheet {
  /** Java constant name, e.g. `MAIN` or `SAVE_LIT`. */
  constant: string;
  codepoint: number;
  /** Measured by the exporter — never authored. */
  advance: number;
}

export interface ScaffoldHotspot {
  /** Java constant name, e.g. `SELECT_SLOTS`. */
  constant: string;
  slots: number[];
}

export interface ScaffoldInput {
  packageName: string;
  /** Class prefix, e.g. `Kiosk` -> KioskGlyphs / KioskLayout / KioskGlyphsTest. */
  className: string;
  base: ScaffoldSheet;
  overlays: ScaffoldSheet[];
  hotspots: ScaffoldHotspot[];
  /** Where the shift lives, e.g. `mymodule.gui.kiosk-title-shift`. */
  shiftConfigKey: string;
}

const hex = (codepoint: number): string => "0x" + codepoint.toString(16).toUpperCase();

export function glyphsJava(input: ScaffoldInput): string {
  const sheets = [input.base, ...input.overlays];
  const constants = sheets
    .map(
      (sheet) =>
        `    public static final Sheet ${sheet.constant} = new Sheet(${hex(sheet.codepoint)}, ${sheet.advance});`,
    )
    .join("\n");

  return `package ${input.packageName};

import net.kyori.adventure.key.Key;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.NamedTextColor;

/**
 * Every drawn piece of the ${input.className} screen, as codepoints, and the arithmetic
 * that stacks them. Generated by Slotify; the advances are measured from the PNGs
 * (rightmost opaque column + 2) and must be re-measured after any redraw.
 *
 * <p>The shift comes from configuration (<code>${input.shiftConfigKey}</code>); the
 * ascent lives in the resource pack's gui.json and no command can tune it.
 */
public final class ${input.className}Glyphs {

    /** The font every chest background on this server is drawn in. */
    public static final Key GUI_FONT = Key.key("minecraft", "gui");

${constants}

    private ${input.className}Glyphs() {
    }

    /** One sheet in the pack: what to draw, and how far drawing it moves the cursor. */
    public record Sheet(int codepoint, int advance) {

        public Component glyph() {
            // WHITE is load-bearing: an untinted title renders the artwork at a quarter
            // brightness in the vanilla dark grey.
            return Component.text(new String(Character.toChars(this.codepoint)))
                .font(GUI_FONT)
                .color(NamedTextColor.WHITE);
        }
    }

    /**
     * A layered screen title: the base sheet, then each overlay drawn back at the base's
     * own origin. Every overlay backtracks by the advance of the sheet drawn immediately
     * before it — not the base's, and not a constant.
     */
    public static Component title(int shiftPixels, Sheet base, Sheet... overlays) {
        var built = Component.text().append(spacer(shiftPixels)).append(base.glyph());
        int drawn = base.advance();

        for (Sheet overlay : overlays) {
            if (overlay == null) {
                continue;
            }

            built.append(spacer(-drawn)).append(overlay.glyph());
            drawn = overlay.advance();
        }

        return built.build();
    }

    /** A run of space characters moving the cursor by {@code pixels}, in the GUI font. */
    public static Component spacer(int pixels) {
        if (pixels == 0) {
            return Component.empty();
        }

        return Component.text(spacerString(pixels)).font(GUI_FONT);
    }

    /**
     * The {@code space} provider at U+E8D0.. (negative) and U+E8D8.. (positive), powers
     * of two up to 64. It loops until the distance is spent instead of clamping — a
     * copied 127px clamp lays a wide backtrack's overlay off by the difference, silently.
     */
    public static String spacerString(int pixels) {
        int remaining = Math.abs(pixels);
        int base = pixels < 0 ? 0xE8D0 : 0xE8D8;
        StringBuilder out = new StringBuilder();

        for (int index = 6; index >= 0 && remaining > 0; index--) {
            int step = 1 << index;

            while (remaining >= step) {
                out.appendCodePoint(base + index);
                remaining -= step;
            }
        }

        return out.toString();
    }
}
`;
}

export function layoutJava(input: ScaffoldInput): string {
  const constants = input.hotspots
    .map(
      (hotspot) =>
        `    public static final int[] ${hotspot.constant} = {${hotspot.slots.join(", ")}};`,
    )
    .join("\n\n");

  return `package ${input.packageName};

/**
 * The clickable geometry of the ${input.className} screen: raw container slot indices,
 * exactly what {@code InventoryClickEvent.getRawSlot()} reports. Generated by Slotify
 * from the hotspots painted in the editor.
 *
 * <p>A button wider than one slot is several slots all doing the same thing; a button
 * straddling two rows binds both rows. Painted slots stay empty — an item placed on one
 * covers the artwork.
 */
public final class ${input.className}Layout {

${constants}

    private ${input.className}Layout() {
    }
}
`;
}

export function glyphsTestJava(input: ScaffoldInput): string {
  const cls = input.className;
  const overlayList = input.overlays.map((sheet) => `${cls}Glyphs.${sheet.constant}`).join(", ");
  const stacked =
    input.overlays.length > 0
      ? `
    @Test
    public void overlaysAllLandOnTheBaseOrigin() {
        int[] origins = originsOf(${cls}Glyphs.title(-8, ${cls}Glyphs.${input.base.constant}, ${overlayList}));

        for (int origin : origins) {
            assertEquals(-8, origin);
        }
    }
`
      : "";

  return `package ${input.packageName};

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.serializer.plain.PlainTextComponentSerializer;
import org.junit.Test;

/**
 * The layering arithmetic of ${cls}Glyphs, replayed the way the client would: spacers
 * move the cursor, a sheet is drawn where the cursor is and then advances it.
 * Generated by Slotify alongside the class it tests.
 */
public final class ${cls}GlyphsTest {

    private static int spacerAdvance(int codepoint) {
        if (codepoint >= 0xE8D0 && codepoint <= 0xE8D6) {
            return -(1 << (codepoint - 0xE8D0));
        }

        if (codepoint >= 0xE8D8 && codepoint <= 0xE8DE) {
            return 1 << (codepoint - 0xE8D8);
        }

        throw new AssertionError("Not a spacer codepoint: U+" + Integer.toHexString(codepoint));
    }

    private static int advanceFor(int codepoint) {
${[input.base, ...input.overlays]
  .map(
    (sheet) => `        if (codepoint == ${hex(sheet.codepoint)}) {
            return ${cls}Glyphs.${sheet.constant}.advance();
        }`,
  )
  .join("\n\n")}

        throw new AssertionError("Unknown sheet: U+" + Integer.toHexString(codepoint));
    }

    private static int[] originsOf(Component title) {
        String flat = PlainTextComponentSerializer.plainText().serialize(title);
        int cursor = 0;
        int[] origins = new int[16];
        int drawn = 0;

        for (int index = 0; index < flat.length(); ) {
            int codepoint = flat.codePointAt(index);
            index += Character.charCount(codepoint);

            if ((codepoint >= 0xE8D0 && codepoint <= 0xE8D6) || (codepoint >= 0xE8D8 && codepoint <= 0xE8DE)) {
                cursor += spacerAdvance(codepoint);
                continue;
            }

            origins[drawn++] = cursor;
            cursor += advanceFor(codepoint);
        }

        int[] out = new int[drawn];
        System.arraycopy(origins, 0, out, 0, drawn);
        return out;
    }

    @Test
    public void everyDistanceInRangeIsExact() {
        for (int pixels = -600; pixels <= 600; pixels++) {
            int total = 0;
            String spacer = ${cls}Glyphs.spacerString(pixels);

            for (int index = 0; index < spacer.length(); ) {
                int codepoint = spacer.codePointAt(index);
                total += spacerAdvance(codepoint);
                index += Character.charCount(codepoint);
            }

            assertEquals("at " + pixels, pixels, total);
        }
    }

    @Test
    public void zeroEmitsNothing() {
        assertTrue(${cls}Glyphs.spacerString(0).isEmpty());
    }

    @Test
    public void aBareSheetStartsAtTheShift() {
        int[] origins = originsOf(${cls}Glyphs.title(-8, ${cls}Glyphs.${input.base.constant}));
        assertEquals(1, origins.length);
        assertEquals(-8, origins[0]);
    }
${stacked}}
`;
}

/** The three files, keyed by their path under `src/{main,test}/java`. */
export function scaffoldFiles(input: ScaffoldInput): Record<string, string> {
  const dir = input.packageName.replace(/\./g, "/");
  return {
    [`src/main/java/${dir}/${input.className}Glyphs.java`]: glyphsJava(input),
    [`src/main/java/${dir}/${input.className}Layout.java`]: layoutJava(input),
    [`src/test/java/${dir}/${input.className}GlyphsTest.java`]: glyphsTestJava(input),
  };
}

/** A one-line summary per sheet, the shape build_sheets.py prints. */
export function advanceTable(input: ScaffoldInput): string {
  const rows = [input.base, ...input.overlays].map(
    (sheet) =>
      `${sheet.constant.toLowerCase().padEnd(24)} ${formatCodepoint(sheet.codepoint)}  advance ${sheet.advance}`,
  );
  return rows.join("\n") + "\n";
}
